fix browser name and optimize

diff --git a/.github/workflows/cypress-crossPlatform.yml b/.github/workflows/cypress-crossPlatform.yml
--- a/.github/workflows/cypress-crossPlatform.yml
+++ b/.github/workflows/cypress-crossPlatform.yml
@@ -17,24 +17,24 @@ jobs:
     strategy:
       matrix:
         include:
-            - os: ubuntu-latest
-              browser: chrome
-            - os: ubuntu-latest
-              browser: firefox
-            - os: ubuntu-latest
-              browser: edge
-            - os: windows-latest
-              browser: chrome
-            - os: windows-latest
-              browser: firefox
-            - os: windows-latest
-              browser: edge
-            - os: macos-latest
-              browser: chrome
-            - os: macos-latest
-              browser: firefox
-            - os: macos-latest
-              browser: edge
+          - os: ubuntu-latest
+            browser: chrome
+          - os: ubuntu-latest
+            browser: firefox
+          - os: ubuntu-latest
+            browser: edge
+          - os: windows-latest
+            browser: chrome
+          - os: windows-latest
+            browser: firefox
+          - os: windows-latest
+            browser: edge
+          - os: macos-latest
+            browser: chrome
+          - os: macos-latest
+            browser: firefox
+          - os: macos-latest
+            browser: edge
 
     runs-on: ${{ matrix.os }}
 
@@ -54,7 +54,7 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 22
-      
+
       - name: Cache Cypress binary
         uses: actions/cache@v4
         with:
@@ -70,7 +70,7 @@ jobs:
           key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
           restore-keys: |
             npm-cache-${{ runner.os }}-
-    
+
       - name: Install Dependencies
         run: npm ci
 
@@ -78,16 +78,12 @@ jobs:
         if: runner.os == 'Windows'
         run: npm install --save-dev cross-env
 
-      - name: Verify Cypress binary
-        run: npx cypress verify
-
       - name: Optionally Reset Environment
         if: ${{ github.event.inputs.reset_env == 'true' }}
         run: npm run reset_frw
 
-      - name: Install Dependencies
-        if: ${{ github.event.inputs.reset_env != 'true' }}
-        run: npm ci
+      - name: Verify Cypress binary
+        run: npx cypress verify
 
       - name: Prepare Allure Report Folder
         run: npm run prereport
@@ -95,7 +91,7 @@ jobs:
       - name: Run Cypress Tests
         run: |
           echo "Running tests on OS: $RUNNER_OS | Browser: $BROWSER"
-          npx cypress run --browser $BROWSER || echo "Tests failed on $BROWSER"
+          npm run test || echo "Tests failed on $BROWSER"
         shell: bash
 
       - name: Upload Allure Results - ${{ matrix.os }}-${{ matrix.browser }}
